[project]
name = "forecasters"
version = "0.0.1"
description = "Unified toolbox for pretrained time-series models to perform forecasting tasks"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
